name: "pre-release"

on:
  push:
    branches:
      - main

jobs:
  
  pre-release:
    name: "Pre-release"
    runs-on: "ubuntu-latest"
    container: ghcr.io/opencs-ontology/ci-worker:main
    
    steps:
      
      - name: "Test directories"
        run: 
          echo $GITHUB_WORKSPACE;
          cd ..;
          pwd ;
          ls
      
      - name: "Download robot.jar"
        uses: wei/wget@v1
        with:
          args: https://github.com/ontodev/robot/releases/download/v1.9.1/robot.jar
      
      - name: "Java install"
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: opencs

      - name: "Package ontology"
        run: python /app/package.py opencs package dev;
      
      - name: "Check directories"
        run: |
          echo "Home"
          echo $HOME
          pwd;
          ls;
          echo "Package";
          cd package;
          ls ;
          cd ..;
          echo "OpenCS";
          cd opencs;
          ls ;
          cd ;
          pwd
          
      - name: "Infer additional assertions"
        run: |
          pwd;
          bash opencs/inference/infer_assertions.sh 1 > /dev/null;
          mkdir output_files; 
          rm output_opencs.ttl opencs2.ttl;
          mv output_opencs2.ttl output_files/inferred_opencs.ttl;
          mv inferred_assertions.ofn output_files/inferred_assertions.ofn;
      
      - name: "check if inference is done"
        run: |
          pwd;
          cd output_files;
          ls;
          head -n100 inferred_opencs.ttl;
          head -n100 inferred_assertions.ofn;
             
      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "dev"
          prerelease: true
          title: "Development build"
          files: package/*
      
      - name: "Prepare ontology files for commit"
        run: |
          mkdir output_files
          gzip -cd package/opencs.ttl.gz > output_files/opencs.ttl
          gzip -cd package/opencs.rdf.gz > output_files/opencs.rdf
          gzip -cd package/opencs.nt.gz > output_files/opencs.nt

      - name: "Push the files to the Github Pages repository"
        uses: "cpina/github-action-push-to-another-repository@main"
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'output_files'
          destination-github-username: 'opencs-ontology'
          destination-repository-name: 'opencs-ontology.github.io'
          user-name: ci-worker
          target-directory: /releases/latest
          target-branch: main
